### PR TITLE
Remove BUNDLE_APP_CONFIG

### PR DESCRIPTION
**Pull request by yykamei**
To run `bundle exec ...` with sudo(8), `BUNDLE_APP_CONFIG` environment variable should also be preserved.

For example, see the following case:

1. Installs gems with `bundle install` as a **root**
    - Note **root** is setting `BUNDLE_APP_CONFIG` environment variable
2. Run `bundle exec ...` as a sudo(8) target user
3. Some errors occur, such as "psych.so is not found"

Because `BUNDLE_APP_CONFIG` environment variable affects only **root**, sudo(8) target users cannot see installed gems by **root**. To solve the problem, sudo(8) target users should have the same `BUNDLE_APP_CONFIG`.

### CODE REVIEW

**Comment by ybiquitous** [comment]
I can't find the documentation about `BUNDLE_APP_CONFIG`, do you know it?

image
https://bundler.io/v2.0/bundle_config.html

**Comment by yykamei** [comment]
To be honest, I don't know. Should we avoid using `BUNDLE_APP_CONFIG` environment variable?

I respected the comment below, but I'm not sure we should try not to create `.bundle` locally.

> # don't create ".bundle" in all our apps

**Comment by ybiquitous** [comment]
It seems this is an undocumented behavior, but `BUNDLE_APP_CONFIG` is surely used on Bundler's code:

https://github.com/bundler/bundler/blob/61a56579cb6232fc02967ea2264b623ee64f16c6/lib/bundler.rb#L242-L248

> Should we avoid using `BUNDLE_APP_CONFIG` environment variable?

No, I don't think we should avoid using it. Bug this is undocumented, so we should be careful when 
 we will update Bundler in the future.

**Comment by wata727** [comment]
> Installs gems with bundle install as a root

Do these gems include NodeHarness? If so, these gems may not have to be installed as root.

**Comment by wata727** [comment]
I'm concerned that the bundler's context of the root user and the context of the analyzer user may be mixed.

**Comment by yykamei** [comment]
> > Installs gems with bundle install as a root
> 
> Do these gems include NodeHarness? If so, these gems may not have to be installed as root.

Yes.

> I'm concerned that the bundler's context of the root user and the context of the analyzer user may be mixed.

I'm optimistic about the mixed context because Bundler can handle the multiple versions of the same gem. For example, this case is possible: a process run by root requires psych 3.0.2 while another run by a sudo(8) target user requires psych 3.1.0.

However, I have a different concern against the `BUNDLE_APP_CONFIG`. Setting Bundler configurations is confusing to me. It took a long time to find the environment variable :face_with_head_bandage:

**Comment by yykamei** [comment]
So, I want to remove the line `ENV BUNDLE_APP_CONFIG=...`.

**Pull request merged**
